language: python
python:
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: sjoerdk
  password:
    secure: oLSiCCU23hOV/loLggR0RjwQ6Ptd9BNrt65PaZvCQZO1wvkIX/t1fbnbhSSOh44h29mZqWdibWWy/Enje3xpqHsuoH+Mavb7Rl5NiJeE5dXKVXSEXKI0Fv2LGo4FXNSLERjrEAXmGENLcyENi48lm0SjgQlFj7kKR8HUa69wZcUPG6KkSpmiEEx0FFZgn5EU22K0eLU+fEt4MQPM4xCSxnIdm7PU5et2/Sz3zRh7WQHuAMl+s38oBzh6Hr0FcI80ShxQqlIvJOYbDADIIdGvKrGjLWe/rozNe5HSVUb50KGa8Ga6rDNAxhzoJMf+abhC6tjPwifN8b9vCI9UPkWSlLRLqsuFkas+3gS0VH6M4ChJaQL4+EQ1DfOEHxaH5GUOzNElkNgqNZCplAw+3qJzHIuGi6w5LQQ8aoeZFjbSjn7PaaUuXRucy9eYZmOKOTJD3SsxduKHCEy7ZPIxgiy/4QkxwqWe18jBYGd78IZmGQY+HQdGES/r1Grvr2X5LgwEycpt2GAhhnnwULffKybwV5VNRow/YBtwIlljkF2POXvXjiK343rFYkjsBBXV0x4HpwiKL7z15mqlBa6CnhvI11c/I5mXGsKvUiO/gv5cWZwX1KeOwsBy8r7NotTToGb9nr8CRTVvKPQDSNkRSZWANtvJ3kiYVhk+0NdgZExum+E=
  on:
    tags: true
    all_branches: true
    repo: sjoerdk/icaclswrap
    python: 3.6
